# Generated by Django 6.0.2 on 2026-02-26 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_ctchistory_employeebankdetail_employeecompliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(choices=[('offer_letter', 'Offer Letter Signed'), ('id_proof', 'Government ID Proof'), ('address_proof', 'Address Proof'), ('education_cert', 'Education Certificates'), ('experience_letter', 'Experience Letter'), ('pan_card', 'PAN Card'), ('bank_details', 'Bank Details Form'), ('nda_signed', 'NDA / Policy Signed'), ('it_assets', 'IT Assets Issued'), ('induction_done', 'Induction Completed')], max_length=50)),
                ('item_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='hackathon.employee')),
            ],
            options={
                'ordering': ['item_key'],
                'unique_together': {('employee', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_on', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hackathon.onboardingchecklist')),
            ],
        ),
    ]
