# Generated by Django 6.0.2 on 2026-02-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_onboardingchecklist_onboardingdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to='hackathon.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
