# Generated by Django 6.0.2 on 2026-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_rolechangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctchistory',
            name='new_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctchistory',
            name='old_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
